#!/bin/sh

export HOME="/afs/cern.ch/exp/totem/scratch/jkaspar"

source "/cvmfs/cms.cern.ch/cmsset_default.sh"
cd "/afs/cern.ch/work/j/jkaspar/software/ctpps/production/CMSSW_9_4_0/src"
cmsenv

# define directories
job_dir="$JOB_DIR"

(
# run the process
cd "$job_dir"

$COMMAND

) &> "$job_dir/$JOB_LOG_FILE"
